import React from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
vi.mock('./cloudMode',()=>({CLOUD_MODE:true}));
import {AgentConnectDialog} from './AgentConnectDialog';
import {cloudAgentPrompt} from './cloudAgentPrompt';
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('copies only the short invitation and offers a public instructions link',async()=>{
  HTMLDialogElement.prototype.showModal=vi.fn(function(this:HTMLDialogElement){this.open=true;});
  HTMLDialogElement.prototype.close=vi.fn();
  const writeText=vi.fn().mockResolvedValue(undefined);
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText}});
  render(<AgentConnectDialog open onClose={()=>{}} origin="https://agartha.example" plotId="plot-4--2"/>);
  fireEvent.click(screen.getByRole('button',{name:'Copy invite',hidden:true}));
  await waitFor(()=>expect(writeText).toHaveBeenCalledWith(cloudAgentPrompt('https://agartha.example','plot-4--2')));
  expect(screen.getByRole('link',{name:/Agent guide/,hidden:true}).getAttribute('href')).toBe('/skill.md');
  expect(screen.getByRole('link',{name:/Pricing & details/,hidden:true}).getAttribute('href')).toBe('/agents/blender-billing.md');
  expect(screen.getByText('$0.40 / 5 min')).toBeTruthy();
  expect(screen.getByText(/Prepaid credits: \$5.00 or \$20.00/)).toBeTruthy();
  expect((screen.getByLabelText('Your agent’s instructions') as HTMLTextAreaElement).value.length).toBeLessThan(300);
});
