/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        hover: "var(--hover)",
        active: "var(--active)",
        selected: "var(--selected)",
        "destructive-light": "var(--destructive-light)",
        surface: {
          1: "var(--surface-1)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
          4: "var(--surface-4)",
          5: "var(--surface-5)",
          6: "var(--surface-6)",
          7: "var(--surface-7)",
          8: "var(--surface-8)",
        },
      },
      boxShadow: {
        "surface-1": "var(--shadow-1)",
        "surface-2": "var(--shadow-2)",
        "surface-3": "var(--shadow-3)",
        "surface-4": "var(--shadow-4)",
        "surface-5": "var(--shadow-5)",
        "surface-6": "var(--shadow-6)",
        "surface-7": "var(--shadow-7)",
        "surface-8": "var(--shadow-8)",
      },
      borderRadius: {
        lg: "var(--radius)",
      },
    },
  },
  plugins: [],
};
