import { defineTable } from 'convex/server';
import { v } from 'convex/values';
import { proposalTables } from '../cloud/proposalSchema';
import { objectValue } from './model';
const definition=v.union(v.object({kind:v.literal('mesh'),name:v.string(),description:v.string(),geometry:v.object({positions:v.array(v.number()),indices:v.array(v.number()),normals:v.array(v.number()),uvs:v.optional(v.array(v.number())),uvs1:v.optional(v.array(v.number())),colors:v.optional(v.array(v.number())),bounds:v.array(v.number())})}),v.object({kind:v.literal('asset'),name:v.string(),description:v.string(),objects:v.array(objectValue),bounds:v.array(v.number())}),v.object({kind:v.literal('shader'),name:v.string(),description:v.string(),expression:v.string(),usesTime:v.boolean()}));
const roomEnvironmentValue=v.object({preset:v.union(v.literal('daylight'),v.literal('golden-hour'),v.literal('moonlit')),exposure:v.number(),haze:v.number(),bloom:v.number(),sunAzimuth:v.number(),sunElevation:v.number()});
export const sceneTables = {
  ...proposalTables,
  sceneMeshCosts:defineTable({gridId:v.string(),meshId:v.string(),triangles:v.number()}).index('by_mesh',['gridId','meshId']),
  sceneLibrary: defineTable({gridId:v.string(),libraryId:v.string(),kind:v.union(v.literal('asset'),v.literal('shader'),v.literal('mesh')),definition,author:v.string(),agentId:v.string(),createdAt:v.number()}).index('by_grid_entry',['gridId','libraryId']).index('by_kind',['gridId','kind']),
  sceneWorlds: defineTable({ worldId:v.string(), name:v.string(), brief:v.string(), briefVersion:v.number(), publicRead:v.boolean(), environment:v.optional(roomEnvironmentValue), environmentVersion:v.optional(v.number()), gridId:v.optional(v.string()), plotX:v.optional(v.number()), plotZ:v.optional(v.number()),archivedAt:v.optional(v.number()),lifecycleVersion:v.optional(v.number()),ownerVersion:v.optional(v.number()),proposalSequence:v.optional(v.number()) }).index('by_world',['worldId']).index('by_grid_cell',['gridId','plotX','plotZ']),
  sceneAgents: defineTable({ worldId:v.string(), agentId:v.string(), name:v.string(), tokenHash:v.string(), cloudSessionId:v.optional(v.id('cloudSessions')),cloudCredentialVersion:v.optional(v.number()), revoked:v.boolean(), canCurate:v.boolean(), objectsAllocated:v.number(), publishedEntries:v.optional(v.number()), expiresAt:v.number(), liveObjects:v.number(), windowStart:v.number(), windowRequests:v.number() }).index('by_token',['tokenHash']).index('by_agent',['worldId','agentId']).index('by_owner',['worldId','canCurate','revoked']),
  sceneInvites: defineTable({ worldId:v.string(), tokenHash:v.string(), expiresAt:v.number(), remaining:v.number() }).index('by_token',['tokenHash']),
  sceneObjects: defineTable({ worldId:v.string(), objectId:v.string(), owner:v.string(), author:v.optional(v.string()), version:v.number(), region:v.string(), deleted:v.boolean(), object:v.optional(objectValue) }).index('by_object',['worldId','objectId']).index('by_region',['worldId','region','deleted']),
  sceneReceipts: defineTable({ worldId:v.string(), agentId:v.string(), requestId:v.string(), payloadHash:v.string(), changed:v.array(v.object({id:v.string(),version:v.number()})), createdAt:v.number() }).index('by_request',['worldId','agentId','requestId']).index('by_time',['createdAt']),
  sceneActivity: defineTable({ worldId:v.string(), region:v.string(), agentId:v.string(), author:v.string(), message:v.string(), requestId:v.string(), createdAt:v.number() }).index('by_region',['worldId','region']).index('by_time',['createdAt']),
};
