"""Blender-side startup for the pinned upstream Blender MCP add-on."""
from __future__ import annotations

import os
from pathlib import Path

from .config import ADDON_PORT, PROJECT_FILE, WORKSPACE

READY_FILE = WORKSPACE / ".blender-mcp-ready"


def build_bootstrap_script(project_file: Path = PROJECT_FILE, ready_file: Path = READY_FILE) -> str:
    """Return a deterministic script suitable for ``blender --python-expr``."""
    project = str(project_file)
    ready = str(ready_file)
    return f'''# generated by agartha-blender-mcp; executed by Blender's main thread
import bpy, os, pathlib, sys, socket
from bpy.app.handlers import persistent

PROJECT = {project!r}
READY = {ready!r}
ADDON_PATH = os.environ.get("BLENDER_MCP_ADDON", "/opt/blender-mcp/addon.py")
ADDON_MODULE = os.environ.get("BLENDER_MCP_ADDON_MODULE", pathlib.Path(ADDON_PATH).stem)
if pathlib.Path(ADDON_PATH).is_file():
    sys.path.insert(0, str(pathlib.Path(ADDON_PATH).parent))

if pathlib.Path(PROJECT).is_file():
    bpy.ops.wm.open_mainfile(filepath=PROJECT, load_ui=True, use_scripts=False)

try:
    bpy.ops.preferences.addon_enable(module=ADDON_MODULE)
except Exception:
    bpy.ops.preferences.addon_enable(module="blender_mcp.addon")

os.environ["DISABLE_TELEMETRY"] = "true"
os.environ.setdefault("BLENDER_MCP_PORT", {str(ADDON_PORT)!r})
prefs = bpy.context.preferences
addon_preferences = getattr(prefs.addons.get(ADDON_MODULE), "preferences", None)
if addon_preferences is not None and hasattr(addon_preferences, "telemetry_consent"):
    addon_preferences.telemetry_consent = False
scene = bpy.context.scene
for name in ("blendermcp_use_polyhaven", "blendermcp_use_hyper3d", "blendermcp_use_hunyuan3d", "blendermcp_use_sketchfab", "blendermcp_use_polypizza"):
    if hasattr(scene, name): setattr(scene, name, False)
try:
    if not getattr(getattr(bpy.types, "blendermcp_server", None), "running", False):
        bpy.ops.blendermcp.start_server()
except Exception:
    pass

@persistent
def _agartha_load_post(_dummy):
    os.environ["DISABLE_TELEMETRY"] = "true"
    os.environ.setdefault("BLENDER_MCP_PORT", str({ADDON_PORT!r}))

if _agartha_load_post not in bpy.app.handlers.load_post:
    bpy.app.handlers.load_post.append(_agartha_load_post)

def _ready():
    if not getattr(getattr(bpy.types, "blendermcp_server", None), "running", False):
        return 0.25
    try:
        with socket.create_connection(("127.0.0.1", int(os.environ.get("BLENDER_MCP_PORT", "9876"))), timeout=0.2):
            pass
    except OSError:
        return 0.25
    pathlib.Path(READY).write_text("ready\\n", encoding="utf-8")
    return None

if not bpy.app.timers.is_registered(_ready):
    bpy.app.timers.register(_ready, first_interval=0.25, persistent=True)

# Blender exits after evaluating a background --python-expr.  In batch mode,
# keep its main thread alive and drain the add-on queue directly; this preserves
# the add-on's requirement that bpy commands run on Blender's main thread.
if os.environ.get("BLENDER_MCP_BATCH_MODE") == "1":
    server = getattr(bpy.types, "blendermcp_server", None)
    if server is not None and server.running:
        pathlib.Path(READY).write_text("ready\\n", encoding="utf-8")
        while server.running:
            server._drain_command_queue()
            import time; time.sleep(0.05)
'''


def configure_blender() -> None:
    """Configure the running Blender process and publish add-on readiness."""
    import bpy  # type: ignore
    import sys

    project = Path(os.environ.get("BLENDER_MCP_PROJECT_FILE", str(PROJECT_FILE)))
    ready = Path(os.environ.get("BLENDER_MCP_READY_FILE", str(READY_FILE)))
    addon_path = Path(os.environ.get("BLENDER_MCP_ADDON", "/opt/blender-mcp/addon.py"))
    if addon_path.is_file():
        sys.path.insert(0, str(addon_path.parent))
    if project.is_file():
        bpy.ops.wm.open_mainfile(filepath=str(project), load_ui=True, use_scripts=False)
    module = os.environ.get("BLENDER_MCP_ADDON_MODULE", "addon")
    try:
        bpy.ops.preferences.addon_enable(module=module)
    except Exception:
        bpy.ops.preferences.addon_enable(module="blender_mcp.addon")
    os.environ["DISABLE_TELEMETRY"] = "true"
    os.environ.setdefault("BLENDER_MCP_PORT", str(9876))
    addon_prefs = getattr(bpy.context.preferences.addons.get(module), "preferences", None)
    if addon_prefs is not None and hasattr(addon_prefs, "telemetry_consent"):
        addon_prefs.telemetry_consent = False
    for name in ("blendermcp_use_polyhaven", "blendermcp_use_hyper3d", "blendermcp_use_hunyuan3d", "blendermcp_use_sketchfab", "blendermcp_use_polypizza"):
        if hasattr(bpy.context.scene, name):
            setattr(bpy.context.scene, name, False)
    if not getattr(getattr(bpy.types, "blendermcp_server", None), "running", False):
        bpy.ops.blendermcp.start_server()
    ready.write_text("ready\n", encoding="utf-8")
