export const STARTER_DEFINITIONS = [
  { stem: 'commons', id: 'the-commons', name: 'The Commons', ground: .1,
    description: 'A timber gathering hall, curved pond, grove and connected stepping-stone paths, with an open western clearing.',
    component: 'Carved gathering bench', componentDescription: 'A crafted timber bench with shaped ends and independent editable parts.' },
  { stem: 'fern_hollow', id: 'plot-0--1', name: 'Fern Hollow', ground: .1,
    description: 'An ancient leaning tree and exposed roots frame a fern-lined stream and mossy footbridge. The front-right clearing remains available.',
    component: 'Ancient rooted tree', componentDescription: 'A leaning woodland tree with exposed roots and layered foliage.' },
  { stem: 'sky_workshop', id: 'plot-1-0', name: 'Sky Workshop', ground: .1,
    description: 'A crafted timber and brass workshop with curved canopy, armillary, assembly terraces, survey telescope and an open building yard. Includes editable named components.',
    component: 'Celestial armillary instrument', componentDescription: 'An articulated brass armillary with meridian rings, degree marks, globe and pedestal.' },
  { stem: 'ochre_court', id: 'plot-0-1', name: 'Ochre Court', ground: -.2,
    description: 'A carved sandstone arch, sundial and sunken court with layered masonry, vessels and a clear processional approach.',
    component: 'Carved sandstone arch', componentDescription: 'A monumental masonry arch with stepped feet, relief bands and individually editable voussoirs.' },
  { stem: 'rolling_meadow', id: 'plot--1-0', name: 'Rolling Meadow', ground: .1,
    description: 'Contoured meadow terraces rise toward a crafted windmill, with dry-stone walls, a stream crossing, flowers and open grass for future building.',
    component: 'Crafted meadow windmill', componentDescription: 'A small crafted windmill with lattice sails, door framing and layered construction.' },
  { stem: 'quiet_beginning', id: 'plot--1--1', name: 'A Quiet Beginning', ground: .1,
    description: 'A stone moon gate, red maples, meditation deck and raked stone garden frame a generous quiet clearing.',
    component: 'Stone moon gate', componentDescription: 'A circular stone gateway assembled from individually jointed segments.' },
  { stem: 'next_chapter', id: 'plot-1--1', name: 'The Next Chapter', ground: .1,
    description: 'A fan-roof reading pavilion, unfinished construction bay and small reading amphitheater leave space for the next contribution.',
    component: 'Reading bench and book cart', componentDescription: 'An editable reading bench and small book cart with books and joinery.' },
  { stem: 'open_ground', id: 'plot--1-1', name: 'Open Ground', ground: .1,
    description: 'A low formal garden with a compass meeting stone, curved benches and small parterres preserves an open central building area.',
    component: 'Curved garden bench', componentDescription: 'A curved timber garden bench with radial slats, stone feet and shaped aprons.' },
  { stem: 'common_future', id: 'plot-1-1', name: 'Common Future', ground: .1,
    description: 'A sweeping teal-tiled tea pavilion and rain garden with viewing seats, reeds and crafted courtyard details.',
    component: 'Tea table and service', componentDescription: 'A crafted tea table with an independently editable tea service and small furnishings.' },
] as const;
